package module2;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class DoctorProfileUI extends javax.swing.JFrame {
     private java.util.List<Staff> temporaryDoctorDb = new java.util.ArrayList<>();
    /**
     * Creates new form DoctorProfileUI
     */
    public DoctorProfileUI() {
        initComponents();
        DatabaseConfig.initializeDatabase();
        refreshUiTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtLicense = new javax.swing.JTextField();
        cmbSpecialisation = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctors = new javax.swing.JTable();
        btnTopsis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Doctor Profile Management");

        jLabel2.setText("Doctor ID:");

        jLabel3.setText("Full Name:");

        jLabel4.setText("Email:");

        jLabel5.setText("License Number:");

        txtID.setText(" ");

        cmbSpecialisation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Surgery", "Cardiology", "Pediatrics", "Internal Medicine" }));

        jLabel6.setText("Specialisation:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblDoctors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Doctor ID", "Full Name", "Email", "Specialisation", "License Number"
            }
        ));
        jScrollPane1.setViewportView(tblDoctors);

        btnTopsis.setText("Rank Priority (TOPSIS)");
        btnTopsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopsisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(484, 484, 484))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbSpecialisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAdd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnUpdate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDelete)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnTopsis)))))))
                        .addContainerGap(282, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbSpecialisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnTopsis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
            // 1. ERROR HANDLING: Validation check for blank entries
if (txtID.getText().trim().isEmpty() || txtName.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Validation Error: Staff ID and Name are required fields!", "Input Failure", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Use Factory Pattern
        Staff newDoc = StaffFactory.createStaff(
            "DOCTOR",
            txtID.getText().trim(),
            txtName.getText().trim(),
            txtEmail.getText().trim(),
            cmbSpecialisation.getSelectedItem().toString(),
            txtLicense.getText().trim()
        );

        // Save to Database
        String sql = "INSERT INTO doctors (staffID, name, email, specialisation, licenseNumber) VALUES (?, ?, ?, ?, ?)";
        try (java.sql.Connection conn = DatabaseConfig.getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, newDoc.getStaffID());
            pstmt.setString(2, newDoc.getName());
            pstmt.setString(3, newDoc.getEmail());
            
            if (newDoc instanceof Doctor) {
                pstmt.setString(4, ((Doctor) newDoc).getSpecialisation());
                pstmt.setString(5, ((Doctor) newDoc).getLicenseNumber());
            }
            
            pstmt.executeUpdate(); 
            javax.swing.JOptionPane.showMessageDialog(this, "Create Success: Profile saved securely to SQLite database!");
            refreshUiTable(); 
            clearInputFields();
        }
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Database Error: ID already exists! \nDetail: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Processing Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    String searchId = txtID.getText().trim();
 if (searchId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a Doctor ID to execute deletion.", "Missing ID", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirmation = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete Doctor [" + searchId + "] permanently?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirmation != javax.swing.JOptionPane.YES_OPTION) return;

    try {
        // Delete from Database
        String sql = "DELETE FROM doctors WHERE staffID=?";
        try (java.sql.Connection conn = DatabaseConfig.getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, searchId);
            int rowsAffected = pstmt.executeUpdate();
            
            if (rowsAffected > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Delete Success: Record deleted from database cleanly.");
                refreshUiTable(); 
                clearInputFields();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Delete Failure: Doctor ID [" + searchId + "] does not exist in database table. Make sure to click ADD to create it first!", "Not Found", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Deletion Failure: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    String searchId = txtID.getText().trim();
    if (searchId.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a Doctor ID to execute deletion.", "Missing Information", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirmation = javax.swing.JOptionPane.showConfirmDialog(this, "Are you certain you want to delete profile ID [" + searchId + "]?", "Confirm Removal", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirmation != javax.swing.JOptionPane.YES_OPTION) return;

      try {
        // DATABASE CRUD (DELETE)
        String sql = "DELETE FROM doctors WHERE staffID=?";
        
        try (java.sql.Connection conn = DatabaseConfig.getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            pstmt.setString(1, searchId);
            int rowsAffected = pstmt.executeUpdate();
            
            if (rowsAffected > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Delete Success: Record deleted from database cleanly.");
                refreshUiTable(); // Refresh table view grid
                clearInputFields();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Delete Failure: Doctor ID does not exist in database.", "Not Found", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Deletion Failure: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
      
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnTopsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopsisActionPerformed
        // TODO add your handling code here:
    java.util.List<TopsisRankingEngine.CandidateDoctor> candidates = new java.util.ArrayList<>();
    // Simulate real doctor metric evaluation parameters
    candidates.add(new TopsisRankingEngine.CandidateDoctor("Dr. Adam (Exp: 10yrs, Workload: 40hrs, Rating: 4.8)", 10, 40, 4.8));
    candidates.add(new TopsisRankingEngine.CandidateDoctor("Dr. Sarah (Exp: 2yrs, Workload: 15hrs, Rating: 4.2)", 2, 15, 4.2));
    candidates.add(new TopsisRankingEngine.CandidateDoctor("Dr. John (Exp: 8yrs, Workload: 48hrs, Rating: 4.9)", 8, 48, 4.9));

    // Run mathematical optimization calculation engine
    java.util.List<TopsisRankingEngine.CandidateDoctor> ranked = TopsisRankingEngine.rankDoctors(candidates);

    StringBuilder result = new StringBuilder("TOPSIS Prioritization Results for On-Call Shifts:\n\n");
    int rank = 1;
    for (TopsisRankingEngine.CandidateDoctor cd : ranked) {
        result.append(rank++).append(". ").append(cd.name)
              .append(" -> TOPSIS Score: ").append(String.format("%.4f", cd.topsisScore)).append("\n");
    }

    javax.swing.JOptionPane.showMessageDialog(this, result.toString(), "MCDM Priority Ranking Optimization", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTopsisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorProfileUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTopsis;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSpecialisation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDoctors;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void refreshUiTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblDoctors.getModel();
        model.setRowCount(0); 
        
        for (Staff s : temporaryDoctorDb) {
            if (s instanceof Doctor) {
                Doctor d = (Doctor) s; 
                model.addRow(new Object[]{
                    d.getStaffID(),
                    d.getName(),
                    d.getEmail(),
                    d.getSpecialisation(),
                    d.getLicenseNumber()
                });
            }
        }
    }

    private void clearInputFields() {
        txtID.setText("");
        txtName.setText("");
        txtEmail.setText("");
        txtLicense.setText("");
        if (cmbSpecialisation.getItemCount() > 0) {
            cmbSpecialisation.setSelectedIndex(0);
        }
    }
}